/* _kbname.hh -- key names
 * Copyright (C) 1995-1998 Markus F.X.J. Oberhumer
 * For conditions of distribution and use, see copyright notice in kb.h
 */

/* WARNING: this file should *not* be used by applications. It is
   part of the implementation of the keyboard library and is
   subject to change. Applications should only use kb.h.
 */

/* DO NOT EDIT - this file is automatically generated by mkkbname.pl */

static const char *const _kb_key_name[128] = {
	"",			/*   0   0x00 */
	"ESC",			/*   1   0x01 */
	"1",			/*   2   0x02 */
	"2",			/*   3   0x03 */
	"3",			/*   4   0x04 */
	"4",			/*   5   0x05 */
	"5",			/*   6   0x06 */
	"6",			/*   7   0x07 */
	"7",			/*   8   0x08 */
	"8",			/*   9   0x09 */
	"9",			/*  10   0x0a */
	"0",			/*  11   0x0b */
	"MINUS",		/*  12   0x0c */
	"EQUAL",		/*  13   0x0d */
	"BACKSPACE",		/*  14   0x0e */
	"TAB",			/*  15   0x0f */
	"Q",			/*  16   0x10 */
	"W",			/*  17   0x11 */
	"E",			/*  18   0x12 */
	"R",			/*  19   0x13 */
	"T",			/*  20   0x14 */
	"Y",			/*  21   0x15 */
	"U",			/*  22   0x16 */
	"I",			/*  23   0x17 */
	"O",			/*  24   0x18 */
	"P",			/*  25   0x19 */
	"OPENBRACE",		/*  26   0x1a */
	"CLOSEBRACE",		/*  27   0x1b */
	"ENTER",		/*  28   0x1c */
	"LCONTROL",		/*  29   0x1d */
	"A",			/*  30   0x1e */
	"S",			/*  31   0x1f */
	"D",			/*  32   0x20 */
	"F",			/*  33   0x21 */
	"G",			/*  34   0x22 */
	"H",			/*  35   0x23 */
	"J",			/*  36   0x24 */
	"K",			/*  37   0x25 */
	"L",			/*  38   0x26 */
	"COLON",		/*  39   0x27 */
	"QUOTE",		/*  40   0x28 */
	"BACKQUOTE",		/*  41   0x29 */
	"LSHIFT",		/*  42   0x2a */
	"BACKSLASH",		/*  43   0x2b */
	"Z",			/*  44   0x2c */
	"X",			/*  45   0x2d */
	"C",			/*  46   0x2e */
	"V",			/*  47   0x2f */
	"B",			/*  48   0x30 */
	"N",			/*  49   0x31 */
	"M",			/*  50   0x32 */
	"COMMA",		/*  51   0x33 */
	"PERIOD",		/*  52   0x34 */
	"SLASH",		/*  53   0x35 */
	"RSHIFT",		/*  54   0x36 */
	"MULTIPLY PAD",		/*  55   0x37 */
	"ALT",			/*  56   0x38 */
	"SPACE",		/*  57   0x39 */
	"CAPSLOCK",		/*  58   0x3a */
	"F1",			/*  59   0x3b */
	"F2",			/*  60   0x3c */
	"F3",			/*  61   0x3d */
	"F4",			/*  62   0x3e */
	"F5",			/*  63   0x3f */
	"F6",			/*  64   0x40 */
	"F7",			/*  65   0x41 */
	"F8",			/*  66   0x42 */
	"F9",			/*  67   0x43 */
	"F10",			/*  68   0x44 */
	"NUMLOCK",		/*  69   0x45 */
	"SCRLOCK",		/*  70   0x46 */
	"7 PAD",		/*  71   0x47 */
	"8 PAD",		/*  72   0x48 */
	"9 PAD",		/*  73   0x49 */
	"MINUS PAD",		/*  74   0x4a */
	"4 PAD",		/*  75   0x4b */
	"5 PAD",		/*  76   0x4c */
	"6 PAD",		/*  77   0x4d */
	"PLUS PAD",		/*  78   0x4e */
	"1 PAD",		/*  79   0x4f */
	"2 PAD",		/*  80   0x50 */
	"3 PAD",		/*  81   0x51 */
	"0 PAD",		/*  82   0x52 */
	"PERIOD PAD",		/*  83   0x53 */
	"SYS REQ",		/*  84   0x54 */
	"",			/*  85   0x55 */
	"LESS",			/*  86   0x56 */
	"F11",			/*  87   0x57 */
	"F12",			/*  88   0x58 */
	"",			/*  89   0x59 */
	"",			/*  90   0x5a */
	"",			/*  91   0x5b */
	"",			/*  92   0x5c */
	"",			/*  93   0x5d */
	"",			/*  94   0x5e */
	"",			/*  95   0x5f */
	"ENTER PAD",		/*  96   0x60 */
	"RCONTROL",		/*  97   0x61 */
	"DIVIDE PAD",		/*  98   0x62 */
	"PRINT",		/*  99   0x63 */
	"ALTGR",		/* 100   0x64 */
	"",			/* 101   0x65 */
	"HOME",			/* 102   0x66 */
	"UP",			/* 103   0x67 */
	"PGUP",			/* 104   0x68 */
	"LEFT",			/* 105   0x69 */
	"RIGHT",		/* 106   0x6a */
	"END",			/* 107   0x6b */
	"DOWN",			/* 108   0x6c */
	"PGDN",			/* 109   0x6d */
	"INSERT",		/* 110   0x6e */
	"DELETE",		/* 111   0x6f */
	"",			/* 112   0x70 */
	"",			/* 113   0x71 */
	"",			/* 114   0x72 */
	"",			/* 115   0x73 */
	"",			/* 116   0x74 */
	"",			/* 117   0x75 */
	"",			/* 118   0x76 */
	"",			/* 119   0x77 */
	"",			/* 120   0x78 */
	"",			/* 121   0x79 */
	"",			/* 122   0x7a */
	"",			/* 123   0x7b */
	"",			/* 124   0x7c */
	"LBANNER",		/* 125   0x7d */
	"RBANNER",		/* 126   0x7e */
	"RMENU",		/* 127   0x7f */
};

/*
vi:ts=4
*/
